# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        semi-supervised object detection: 5
        object detection: 2
        semi-supervised: 2
        weakly-supervised: 2
        consistency: 1
        pseudo labeling: 2

# 通知の閾値
score_threshold: 3
